game:
    time: 60
    friendly-fire: false
    human-respawn: 5
    zombie-respawn: 5

team:
    zombie:
    
    human:

    waiting:
    
spawn:
    zombie:
    
    human:
    
    zombie-hold:
    
    human-hold:
    
    leave:
    
    wait:
    
loadout:
    zombie:
        inven:
            
        armor:
            
        potions:
    
    human:
        inven:
            
        armor:
            
        potions:
    
