name: MCInfection
main: com.gmail.buzziespy.MCInfection.MCInfection
version: 0.6

permissions:
    infect.admin:
        description: Access to all game commands.
        children:
            infect.player: true
    infect.player:
        description: Access to game player commands.
        default: true

commands:
    infect:
       description: Display current settings or reload from config
       usage: /infect <reload>
       permission: infect.admin
    joinwait:
       description: Force-join the waiting (spectator) team.
       usage: /joinspec
       permission: infect.admin
       
    joinhum:
       description: Force-join the human team.
       usage: /joinhum
       permission: infect.admin
    
    joinzom:
       description: Force-join the zombie team.
       usage: /joinzom
       permission: infect.admin
       
    leavegame:
       description: Leave the game.
       usage: /leavegame
       permission: infect.player
       
    teams:
       description: See team rosters.
       usage: /teams
       permission: infect.player
       
    set-human-spawn:
       description: Set a human spawn point.
       usage: /teams
       permission: infect.admin
       
    set-zombie-spawn:
       description: Set a zombie spawn point.
       usage: /teams
       permission: infect.admin
       
    human-spawn:
       description: See human spawn points.
       usage: /teams
       permission: infect.admin
       
    zombie-spawn:
       description: See zombie spawn points.
       usage: /teams
       permission: infect.admin
       
    clear-human-spawn:
       description: Clear human spawn points.
       usage: /teams
       permission: infect.admin
       
    clear-zombie-spawn:
       description: Clear zombie spawn points.
       usage: /teams
       permission: infect.admin
    
    set-human-hold:
       description: Set human holding cell location.
       usage: /teams
       permission: infect.admin
       
    clear-human-hold:
       description: Clear human holding cell location.
       usage: /teams
       permission: infect.admin
       
    set-zombie-hold:
       description: Set zombie holding cell location.
       usage: /teams
       permission: infect.admin
       
    clear-zombie-hold:
       description: Clear zombie holding cell location.
       usage: /teams
       permission: infect.admin
       
    human-hold:
       description: See human holding cell location.
       usage: /teams
       permission: infect.admin
       
    zombie-hold:
       description: See zombie holding cell location.
       usage: /teams
       permission: infect.admin
       
    save-human-loadout:
       description: Save human loadout.
       usage: /teams
       permission: infect.admin
       
    human-loadout:
       description: Clears your inventory and replaces it with human loadout.
       usage: /teams
       permission: infect.admin
       
    save-zombie-loadout:
       description: Save zombie loadout.
       usage: /teams
       permission: infect.admin
       
    zombie-loadout:
       description: Clears your inventory and replaces it with zombie loadout.
       usage: /teams
       permission: infect.admin
       
    save-leave-point:
       description: Save leave point.
       usage: /teams
       permission: infect.admin
       
    leave-point:
       description: See leave point.
       usage: /teams
       permission: infect.admin
       
    save-wait-point:
       description: Save wait point.
       usage: /teams
       permission: infect.admin
       
    wait-point:
       description: See wait point.
       usage: /teams
       permission: infect.admin
       
    joingame:
       description: Join the game.  Your inventory is wiped on entry.
       usage: /joingame
       permission: infect.player
       
    infection-start:
       description: Starts the game.
       usage: /infection-start [gameTime]
       permission: infect.admin
       
    infection-end:
       description: Force-end the game.
       usage: /infection-end
       permission: infect.admin
       
    ff:
       description: Display friendly fire status
       usage: /ff
       permission: infect.player
       
    ffon:
       description: Turn on friendly fire
       usage: /ffon
       permission: infect.admin
       
    ffoff:
       description: Turn off friendly fire
       usage: /ffoff
       permission: infect.admin